/*
 * Ship Routing API
 *
 * Access the global ship routing service via a RESTful API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	server "github.com/natevvv/osm-ship-routing/pkg/server/openapi_server"
)

const plainGraphFile = "graphs/ocean_10k.fmi"
const contractedGraphFile = "contracted_graph.fmi"
const shortcutFile = "shortcuts.txt"
const nodeOrderingFile = "node_ordering.txt"

func main() {
	log.Printf("Loading graph '%s' into memory", plainGraphFile)
	DefaultApiService := server.NewDefaultApiService(plainGraphFile, contractedGraphFile, shortcutFile, nodeOrderingFile)
	DefaultApiController := server.NewDefaultApiController(DefaultApiService)

	router := server.NewRouter(DefaultApiController)
	log.Printf("Server started @ http://localhost:8081")

	log.Fatal(http.ListenAndServe(":8081", router))
}
